cli: check deps

diff --git a/src/cli/reliquary-init b/src/cli/reliquary-init
--- a/src/cli/reliquary-init
+++ b/src/cli/reliquary-init
@@ -2,6 +2,10 @@
 
 set -e
 
+if ! type jq &> /dev/null; then echo "jq dependency missing"; exit; fi
+if ! type xxd &> /dev/null; then echo "xxd dependency missing"; exit; fi
+if ! type curl &> /dev/null; then echo "curl dependency missing"; exit; fi
+
 if [ -z "$RELIQUARY" ]; then
 	RELIQUARY=$HOME/.config/reliquary
 fi
